baseurl = "http://aasted.com/"
title = "Matt Aasted"
languageCode = "en-us"
theme = "hugo_theme_robust"
googleAnalytics = "UA-88094328-1"
contentdir = "content"
layoutdir = "layouts"
publishdir = "../aasted.github.io"
canonifyurls = true

[params]
    author = "Matt Aasted"
    copyright = "© Matt Aasted"
